### ISSUE TITLE
Some examples don't work

### ISSUE THREAD

**Issue by d3lm** [vercel/next.js#25854]
### What example does this report relate to?

See list below

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

/

### Describe the Bug

While testing all examples for [this](https://github.com/vercel/next.js/pull/25853) PR, I ran into a few examples that didn't work. Here's a list:

- [ ] with-webpack-bundle-size-analyzer
  - see #26715
- [x] with-webassembly (fixed in #26440)
  - see #26436
- [x] with-i18n-next-intl (fixed in #25928)
  - `MISSING_OTHER_CLAUSE`
- [x] with-ant-design-mobile (fixed in #25929)
  - missing peer dependencies with `yarn` or our internal package manager `turbo`
- [x] with-kea (fixed in #26069)
  - missing peer dependencies with `yarn` or our internal package manager `turbo` → `@babel/core`
- [x] with-lingui (fixed in #26076)
  - missing peer dependencies with `yarn` or our internal package manager `turbo` → `@babel/core`
  - deprecation warnings
- [x] with-mobx (fixed in #26069)
  - missing peer dependencies with `yarn` or our internal package manager `turbo` → `@babel/core`
- [x] with-mobx-react-lite (fixed in #26069)
  - missing peer dependencies with `yarn` or our internal package manager `turbo` → `@babel/core`
- [x] with-mobx-state-tree (fixed in #26069)
  - missing peer dependencies with `yarn` or our internal package manager `turbo` → `@babel/core`
- [x] with-mobx-state-tree-typescript (fixed in #25589)
  - missing peer dependencies with `yarn` or our internal package manager `turbo` → `@babel/core`
- [x] with-next-page-transitions (fixed in #25901)
  - Warning: viewport meta tags should not be used in _document.js's `<Head>`. https://nextjs.org/docs/messages/no-document-viewport-meta
- [x] with-next-sitemap (fixed in #25866)
  - missing `devDependencies` → `typescript`
- [ ] ssr-caching
- [x] with-rbx-bulma-pro (fixed in #25854)
- [x] with-react-md (fixed in #26001)
  - uses `node-sass` which doesn't work on StackBlitz because it requires a binary and typically involves running an `install` script which builds the package. Would be nice if we could switch to `sass` instead, the `typescript` version of this example also uses sass.
- [x] with-react-multi-carousel (fixed in #25902)
  - `Warning: Each child in a list should have a unique "key" prop`
- [ ] with-reflux
  - `Warning: componentWillMount has been renamed`
- [ ] with-tailwindcss-emotion
  - `matchUtilities` is not a function
  - Cannot find module `with-tailwindcss-emotion/.next/server/pages-manifest.json`
- [x] with-typescript-graphql (fixed in #26010)
- [x] with-urql (fixed in #25987)
  - CORS errors for `https://graphql-pokemon.vercel.app/`, maybe we can add stackblitz.com to the allowed origins

### Expected Behavior

The examples are expected to work locally.

After an example has been fixed, please add a `Preview` section to the `README.md` right above `Deploy your own`.

- Replace `DIRECTORY_NAME` with the directory name you’re adding.

```md
## Preview

Preview the example live on [StackBlitz](http://stackblitz.com/):

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/DIRECTORY_NAME)
```

⚠️ If the example doesn't work on StackBlitz, please let us know and file an issue [here](https://github.com/stackblitz/webcontainer-core).

### To Reproduce

Follow the steps in the `README.md`.

**Comment by vitalybaev** [comment]
Good work, thanks!
`mobx-state-tree-typescript` should be fixed in #25589

**Comment by vitalybaev** [comment]
Could you please convert this list to checkboxes? It would be much better to understand fixed cases 🙏

**Comment by d3lm** [comment]
Yep totally, good point.

**Comment by d3lm** [comment]
@vitalybaev I can verify that the `mobx-state-tree-typescript` works now, but there is still a warning. Would be awesome if we could get rid of it.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

**Comment by akellbl4** [comment]
- The warning in `with-next-page-transitions` has been fixed.
- `with-react-multi-carousel` is fixed as well
- I don't see anything that we can fix in `with-reflux` example. The warning produced by `reflux`. [Reflux](https://github.com/reflux/refluxjs) hasn't got updates last 4 years.

**Comment by d3lm** [comment]
@akellbl4 Thanks for the update! Let me test those examples again and update the checklist accordingly.

**Comment by akellbl4** [comment]
@d3lm good! Let me know if anything causes errors I'm ready to fix it ;)

**Comment by d3lm** [comment]
@akellbl4 I commented on your PRs with updates.

**Comment by lauriskuznecovs** [comment]
I got it working with this:

```
const cacheableResponse = require('cacheable-response')
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })

const handle = app.getRequestHandler()

const ssrCache = cacheableResponse({
  ttl: 1000 * 60, // 1 minute
  getKey: ({ req }) => `${req.url}`,
  get: async ({ req, res, path, query }) => {
    const data = await app.renderToHTML(req, res, path, query)

    // Add here custom logic for when you do not want to cache the page, for
    // example when the page returns a 404 status code:
    if (res.statusCode === 404) {
      res.end(data)
      return
    }

    return { data }
  },
  send: ({ data, res }) => res.send(data)
})

app.prepare().then(() => {
  const server = express()

  server.get('/', (req, res) => ssrCache({ req, res, path: req.path, query: req.query, }))

  server.get('/blog/:id', (req, res) => ssrCache({ req, res, path: req.path, query: req.query, }))

  server.get('*', (req, res) => handle(req, res))

  server.listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```

**Comment by lauriskuznecovs** [comment]
**ssr-caching** example does not work, even with current latest package versions.
I made it working like this, but there is an issue when using **next-i18next**.
locale is not available in from next router, but locales is.

**server.js**
```
const cacheableResponse = require('cacheable-response')
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })

const handle = app.getRequestHandler()

const ssrCache = cacheableResponse({
  ttl: 1000 * 60, // 1 minute
  getKey: ({ req }) => `${req.url}`,
  get: async ({ req, res, path, query }) => {
    const data = await app.renderToHTML(req, res, path, query)

    // Add here custom logic for when you do not want to cache the page, for
    // example when the page returns a 404 status code:
    if (res.statusCode === 404) {
      res.end(data)
      return
    }

    return { data }
  },
  send: ({ data, res }) => res.send(data)
})

app.prepare().then(() => {
  const server = express()

  server.get('/', (req, res) => ssrCache({ req, res, path: req.path, query: req.query, }))

  server.get('/blog/:id', (req, res) => ssrCache({ req, res, path: req.path, query: req.query, }))

  server.get('*', (req, res) => handle(req, res))

  server.listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```
```

**Comment by akellbl4** [comment]
> Warning: componentWillMount has been renamed

> I don't see anything that we can fix in `with-reflux` example. The warning produced by reflux. [Reflux](https://github.com/reflux/refluxjs) hasn't got updates last 4 years.


@leerob what should we do with the example?

**Comment by akellbl4** [comment]
@d3lm here are live examples of fixed items that were merged:

- [`with-page-transition`](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-next-page-transitions)
- [`with-next-sitemap`](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-next-sitemap)
- [`with-react-multi-carousel`](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-react-multi-carousel)

Could you please mark them as resolved?

**Comment by d3lm** [comment]
@akellbl4 Updated the list accordingly. Good job man!

**Comment by vitalybaev** [comment]
@d3lm `with-urql` example has been fixed in #25987. I've also added StackBlitz button in readme. Please check it.

**Comment by d3lm** [comment]
@vitalybaev Awesome! Just checked it and it works. Great work 🙌 🙏

**Comment by vitalybaev** [comment]
`with-react-md` has been merged 👌

**Comment by d3lm** [comment]
Thanks @akellbl4 for fixing the `with-typescript-grapql` exmaple 🎉 🙏

**Comment by akellbl4** [comment]
I'm going to fix all of the examples with missed peer dependencies

**Comment by akellbl4** [comment]
`with-lingui` needs more than just peer dependency.

**Comment by d3lm** [comment]
Do you already know what's breaking it?

**Comment by akellbl4** [comment]
Yes.
It installs the latest version of `@lingui/react`  and some exports were depricated.
I think I can update the example.

**Comment by akellbl4** [comment]
@d3lm something went wrong on StackBlitz :( https://github.com/stackblitz/core/issues/1505

**Comment by akellbl4** [comment]
> d3lm something went wrong on StackBlitz :( stackblitz/core#1505
Ops, that's was my bad. Fixed in https://github.com/vercel/next.js/pull/26091

**Comment by vitalybaev** [comment]
@d3lm thanks for reporting! It has been broken after releasing Next.js 11, that enabled webpack 5 by default. Let's wait my PR to merge 😴

**Comment by d3lm** [comment]
Yay! Has been merged 🙌 Thanks @vitalybaev

**Comment by d3lm** [comment]
I just filed #26715 because the `with-webpack-bundle-size-analyzer` doesn't work anymore. Anyone down to fix this?

**Comment by Cheprer** [comment]
Example `with-typescript-graphql` is currenty not working. The fix above didn't work.

In `lib/resolvers.ts` typescript throws an error and fails to compile.

```
Module '"*.graphqls"' has no exported member 'MutationResolvers'. Did you mean to use 'import MutationResolvers from "*.graphqls"' instead?ts(2614)
```

Ideas how to fix it?

**Comment by balazsorban44** [comment]
Hi, we appreciate the efforts on this, but I believe such an issue like this should not exist. It's way too general and hardly actionable. I suggest opening example-specific issues instead.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
