### ISSUE TITLE
Switchable server runtime

### ISSUE THREAD

**Issue by shuding** [vercel/next.js#31506]
Currently, the SSR streaming (the Fizz architecture enabled with `concurrentFeatures: true`) server is always bundled as a middleware, targeting the web runtime. This behavior is confusing as well as lacking of flexibility. In order to make the runtime switchable between `web` and `node`, there are many necessary changes to be done in the near future:
- [x] Create BaseServer, NextServer and NextWebServer on top of it (#32154).
- [x] Update BaseServer to be runtime agnostic.
  - [x] Node native APIs
    - #31971
    - #31508
    - #31807
    - #32322
    - #33226
    - #33448
    - #33475
    - #33537
    - #36246
    - #36306
  - [x] Req/res
    - #32298
    - #32999
  - [x] 3rd party libs
    - #33499
- [ ] Implement Web APIs in NextWebServer (#33635, #33664).
  - [x] ~Support for passing manifests via constructor options (can be done later)~
  - [x] Support for dynamic routes
  - [ ] Support for rewrites (relies on Edge Function support)
  - [ ] Support for i18n
  - [x] Support for compression (#34723)
- [x] Add Edge Function support to Next.js similar to middleware, use the sandbox if running in Node.js.
- [x] #31317: Introduce a `runtime` option for all pages and API routes, which defaults to `node` and can be configured to `web` (WIP)
- [x] Support custom `_app` and `_app.server` at the same time for different pages. (#35666)
- [x] Statically optimized server pages should also have the flight JSON exported. 

Will probably split this into smaller tasks if needed.

**Comment by karaggeorge** [comment]
Can't edit, but closed http PR in favor of https://github.com/vercel/next.js/pull/32999

**Comment by huozhi** [comment]
In preparation for stability, we are moving usage from pages/ to the new app/ folder as outlined in the Layouts RFC. Server Components will be the default for all routes inside app/. Server Components support is still unstable. Close this task as most of the work are done in 12.2.1. We'll be sharing more information soon on how you can test out early versions of app/.
